service: fishSauce

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  echo:
    handler: bin/main
    events:
      - http:
          path: echo
          method: post